name: Benchmarks

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  benchmark:
    name: Benchmarks
    strategy:
      matrix:
        go-version: ["1.19"]
        platform: ["ubuntu-latest"]

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Run benchmark
        run: go test  -benchmem -run="^$" -bench "^Benchmark" . quamina.net/go/quamina | tee output.txt

      - name: Download previous benchmark data
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@29e55772d85cc51b2a291bde13f33ef9014d2d1f
        with:
          name: Go Benchmark
          tool: "go"

          # Compare results against json from cache
          output-file-path: output.txt
          external-data-json-path: ./cache/benchmark-data.json

          # print job summary in workflow output
          summary-always: true

          # Alert on regression
          alert-threshold: "120%"
          fail-on-alert: true
          comment-on-alert: false

          # Disable github pages, for now.
          auto-push: false
