name: Dependency Review

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  dependency-review:
    strategy:
      matrix:
        go-version: ["1.19"]
        platform: ["ubuntu-latest"]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        
      - name: Dependency Review
        uses: actions/dependency-review-action@733dd5d4a5203f238c33806593ec0f5fc5343d8c