name: Dependency Review

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  dependency-review:
    strategy:
      matrix:
        go-version: ["1.19"]
        platform: ["ubuntu-latest"]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
        
      - name: Dependency Review
        uses: actions/dependency-review-action@f46c48ed6d4f1227fb2d9ea62bf6bcbed315589e