name: Code Linting

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Code Linting
    strategy:
      matrix:
        go-version: ["1.18"]
        platform: ["ubuntu-latest"]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      with:
        fetch-depth: 1
        
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@537aa1903e5d359d0b27dbc19ddd22c5087f3fbc