name: Code Linting

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Code Linting
    strategy:
      matrix:
        go-version: ["1.19"]
        platform: ["ubuntu-latest"]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      with:
        fetch-depth: 1

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
      with:
        go-version: ${{ matrix.go-version }}
      id: go
      
    - name: Restore Go cache
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum', 'testdata/**') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ matrix.go-version }}-
        
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc