name: Code Linting

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Code Linting
    strategy:
      matrix:
        go-version: ["1.19"]
        platform: ["ubuntu-latest"]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 1

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
      with:
        go-version: ${{ matrix.go-version }}
      id: go
      
    - name: Restore Go cache
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum', 'testdata/**') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ matrix.go-version }}-
        
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc